// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDesQ6YqmhXtVrFvJb-OoTUaK-r_EnhfMo',
    appId: '1:264203176225:web:65df55159e7ba81c565660',
    messagingSenderId: '264203176225',
    projectId: 'flutter-chat-app-7b5d8',
    authDomain: 'flutter-chat-app-7b5d8.firebaseapp.com',
    storageBucket: 'flutter-chat-app-7b5d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYdqpGapDBohB2xRyhFMPGxArxYY_zpiI',
    appId: '1:264203176225:android:5dec3b493e4bcad8565660',
    messagingSenderId: '264203176225',
    projectId: 'flutter-chat-app-7b5d8',
    storageBucket: 'flutter-chat-app-7b5d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX8T6x6KE_CnGICkop16EMgfNUG8V0tS8',
    appId: '1:264203176225:ios:da550be44b7078c9565660',
    messagingSenderId: '264203176225',
    projectId: 'flutter-chat-app-7b5d8',
    storageBucket: 'flutter-chat-app-7b5d8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX8T6x6KE_CnGICkop16EMgfNUG8V0tS8',
    appId: '1:264203176225:ios:9543679848e79545565660',
    messagingSenderId: '264203176225',
    projectId: 'flutter-chat-app-7b5d8',
    storageBucket: 'flutter-chat-app-7b5d8.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
